### ISSUE TITLE
The component is not minor version aware

### ISSUE THREAD

**Issue by megian** [appuio/component-openshift4-monitoring#27]
The component currently assumes that OpenShift 4.5 is running. This causes that some rules do not match for example OpenShift 4.7. In 4.7 the SDN OVS pods disappeared. But the component still applies the rules for OpenShift 4.5. 

The alert NodeWithoutOVSPod has been removed: https://github.com/openshift/cluster-network-operator/commit/614e6e165a783089ecada659a3547a41b0a21b5b

## Steps to Reproduce the Problem

  1. Install OpenShift 4.7 and use the component version v1.0.0
  2. Apply the component openshift4-monitoring

## Actual Behavior
The alert NodeWithoutOVSPod does pop up. But his is irrelevant, as OpenShift 4.7 does not require this pods anymore.

A simple workaround is:
```
parameters:
  openshift4_monitoring:
    alerts:
      ignoreNames:
        # OpenShift >=4.7 does not have OVS pods running
        # https://github.com/openshift/cluster-network-operator/commit/614e6e165a783089ecada659a3547a41b0a21b5b
        - NodeWithoutOVSPod
```

## Expected Behavior
The rule import is based on the OpenShift version release-4.x.
