### ISSUE TITLE
SYN_ClusterNotUpgradeable messages not rendered

### ISSUE THREAD

**Issue by mhutter** [appuio/component-openshift4-monitoring#58]
The "Message" annotation for said AlertRule is not rendered and instead displayed verbatim in Prometheus, AlertManager and Opsgenie.

The "original" upstream AlertRule (`ClusterNotUpgradeable`) is rendered as expected in Prometheus.

Ping me in Chat for Prometheus link if required

**Comment by simu** [comment]
As discussed/investigated recently:

* The upstream manifests for `SYN_ClusterNotUpgradeable` (https://github.com/openshift/cluster-version-operator/blob/14d93a158e163f06c2ee936ee29c9c94da7f35fe/install/0000_90_cluster-version-operator_02_servicemonitor.yaml) have an extra level of gotemplates around the Prometheus templates, which the component doesn't render/remove, for example:

```yaml
  - name: cluster-version
    rules:
    - alert: ClusterVersionOperatorDown
      annotations:
        summary: Cluster version operator has disappeared from Prometheus target discovery.
        description: The operator may be down or disabled. The cluster will not be kept up to date and upgrades will not be possible. Inspect the openshift-cluster-version namespace for events or changes to the cluster-version-operator deployment or pods to diagnose and repair. {{ "{{ with $console_url := \"console_url\" | query }}{{ if ne (len (label \"url\" (first $console_url ) ) ) 0}} For more information refer to {{ label \"url\" (first $console_url ) }}/k8s/cluster/projects/openshift-cluster-version.{{ end }}{{ end }}" }}
      expr: |
        absent(up{job="cluster-version-operator"} == 1)
      for: 10m
      labels:
        severity: critical
```

It's not clear to me at the moment how we can solve this problem except for implementing gotemplate rendering in Jsonnet which seems like a large undertaking. I had a quick look for a gotemplate Python library, but the only one I found requires building a shared library by hand which we'd like to avoid if possible.

After experimenting a bit: it should be possible to use Jinja2 rendering, since the examples I've looked at only use the pattern `{{ "..." }}` which needs to be rendered out.

This could be achieved e.g. by doing something like the following in `upstreamManifests` in `component/rules.jsonnet` (untested):

```
local fixupUpstreamManifests(file) =
  local loadfunc = 
    if file == 'cluster-version-operator.yaml' then
      kap.jinja2_template
    else
      kap.yaml_load_stream;
local upstreamManifests = std.flatMap(
  function(file)
    std.parseJson(loadfunc(file)(
      'openshift4-monitoring/manifests/%s/%s' % [ params.manifests_version, file ]
    )),
  std.filter(
    function(file)
      !upstreamManifestsFileExclude(file),
    kap.dir_files_list('openshift4-monitoring/manifests/%s' % [ params.manifests_version ])
  ),
);
```
